version: "3.8"
services:
  web:
    container_name: hfntr-web
    build: .
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./media:/app/media
    networks:
      hifenator:
    restart: always
  nginx:
    container_name: hfntr-nginx
    depends_on:
      - web
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log:/log
      - ./media:/media
    labels:
      - "traefik.http.routers.nginx.rule=Host(`hifenator.rs`)"
      - traefik.http.routers.nginx.entrypoints=web
      - traefik.http.routers.nginx.middlewares=redirect-to-https@docker
      - "traefik.http.routers.nginx-secured.rule=Host(`hifenator.rs`)"
      - traefik.http.routers.nginx-secured.entrypoints=websecure
      - traefik.http.routers.nginx-secured.tls.certresolver=letsencrypt
      - traefik.http.routers.nginx-secured.tls=true
    networks:
      hifenator:
  qcluster:
    container_name: hfntr-qcluster
    depends_on: 
      - web
    build: .
    command: qcluster
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./media:/app/media
    networks:
      hifenator:
    restart: always
networks:
  hifenator:
    external: true
