# Generated by Django 4.0.4 on 2022-04-24 01:16

from django.db import migrations, models
import hfntr.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HyphenatedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_file', models.FileField(upload_to=hfntr.models.get_upload_path, verbose_name='original file')),
                ('new_file', models.FileField(upload_to=hfntr.models.get_upload_path, verbose_name='hyphenated file')),
                ('status', models.IntegerField(choices=[(0, 'Unknown'), (1, 'New'), (2, 'Processing'), (3, 'Finished'), (4, 'Failed')], default=1)),
            ],
            options={
                'verbose_name': 'hyphenated file',
                'verbose_name_plural': 'hyphenated files',
            },
        ),
    ]
