# Generated by Django 4.0.4 on 2022-04-24 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hfntr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hyphenatedfile',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
